Task:
  Dataset:
    name: cifar_dataset
    args:
      data_dir: ./data/cifar
  Model:
    name: CNNCifar
    args:
      num_classes: 10
  Trainer:
    name: ImageClassificationTrainer
    args:
      epochs: 1
      batch_size: 64
      loss_function: nll_loss
      optimizer:
        name: SGD
        args:
          lr: 0.1
          momentum: 0.5
      device: cpu