# task setting
Task:
  Dataset:
    name: mnist_dataset
    args:
      data_dir: ./data/mnist
  Model:
    name: CNNMnist
    args:
      num_channels: 1
      num_classes: 10
  Trainer:
    name: ImageClassificationTrainer
    args:
      epochs: 5
      batch_size: 64
      loss_function: nll_loss
      optimizer:
        name: SGD
        args:
          lr: 0.01
          momentum: 0.5
      device: cpu

# sample setting
Sampler:
  name: UniformSampler
  args:
    num_clients: 20

# FL setting
FL:
  name: federated_average
  rounds: 1

# Noisy level
Noise:
  alpha: 0.3
  mu: 0.35
  sigma: 0.4
  lower: 0
  upper: 1

# selector setting
Selector:
  name: NoiseSelector
  args:
    frac: 0.4

save_path: ./result/